//! Build script: generate the *direct* dependency table shown in the About
//! window's License tab.
//!
//! Strategy:
//!
//! 1. Walk the workspace `Cargo.toml` to collect the `members = [...]` list.
//! 2. For each member crate, parse its `Cargo.toml` `[dependencies]` table
//!    and collect dependency *names* (the table keys). Path deps whose name
//!    starts with `crabport` are filtered out — they're our own crates.
//! 3. Resolve each name to a concrete version by scanning `Cargo.lock` for
//!    the matching `[[package]]` entry.
//! 4. Emit a `pub static ABOUT_DEPENDENCIES: &[(&str, &str)]` to `OUT_DIR`,
//!    included by `src/windows/about.rs`.
//!
//! Only *direct* dependencies of the workspace members are listed —
//! transitive deps of those deps are not. This keeps the About list short
//! and focused on the libraries the project actually chose to depend on.
//!
//! We deliberately avoid a real TOML parser (no extra build-dependency).
//! `Cargo.toml`'s `[dependencies]` table is simple enough that scanning for
//! `key = ...` lines under the right section header is sufficient.

use std::collections::BTreeMap;
use std::fs;
use std::path::PathBuf;

fn main() {
    let manifest_dir =
        PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let workspace_root = manifest_dir.parent().expect("workspace root");
    let workspace_toml = workspace_root.join("Cargo.toml");
    let lock_path = workspace_root.join("Cargo.lock");

    // ---- 1. Collect workspace member directories ----
    let members = parse_workspace_members(
        &fs::read_to_string(&workspace_toml)
            .unwrap_or_else(|e| panic!("read {}: {e}", workspace_toml.display())),
    );

    // ---- 2. Collect direct dependency names from each member's Cargo.toml ----
    let mut dep_names: std::collections::BTreeSet<String> = std::collections::BTreeSet::new();
    for member_rel in &members {
        // `members` entries are relative to the workspace root (e.g.
        // "crabport-ui"). Some may be glob patterns; we only handle literal
        // paths here, which is all this workspace uses.
        let member_toml = workspace_root.join(member_rel).join("Cargo.toml");
        let text = match fs::read_to_string(&member_toml) {
            Ok(t) => t,
            Err(_) => continue,
        };
        for name in parse_dependencies_keys(&text) {
            // Skip our own workspace crates.
            if name.to_lowercase().starts_with("crabport") {
                continue;
            }
            dep_names.insert(name);
        }
    }

    // ---- 3. Resolve each name to a version via Cargo.lock ----
    let lock_text = fs::read_to_string(&lock_path)
        .unwrap_or_else(|e| panic!("read {}: {e}", lock_path.display()));
    let lock_versions = parse_lock_packages(&lock_text);

    let mut deps: Vec<(String, String)> = Vec::new();
    for name in dep_names {
        if let Some(version) = lock_versions.get(&name) {
            deps.push((name, version.clone()));
        }
        // If a direct dep isn't found in Cargo.lock (shouldn't happen for a
        // successfully built workspace), we silently omit it rather than
        // panic — the About list is best-effort.
    }

    // Sort by name for a stable, scannable list.
    deps.sort_by(|a, b| a.0.cmp(&b.0));

    // ---- 4. Emit ----
    let mut out = String::new();
    out.push_str("// Auto-generated by `crabport-ui/build.rs`.\n");
    out.push_str("// Direct dependencies of the workspace member crates, resolved to\n");
    out.push_str("// concrete versions via Cargo.lock. Do not edit by hand.\n\n");
    out.push_str("pub static ABOUT_DEPENDENCIES: &[(&str, &str)] = &[\n");
    for (n, v) in &deps {
        out.push_str(&format!("    ({:?}, {:?}),\n", n, v));
    }
    out.push_str("];\n");

    let out_dir = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR"));
    let dest = out_dir.join("about_dependencies.rs");
    fs::write(&dest, out).unwrap_or_else(|e| panic!("write {}: {e}", dest.display()));

    println!("cargo:rerun-if-changed=../Cargo.toml");
    println!("cargo:rerun-if-changed=../Cargo.lock");
    for member_rel in &members {
        println!("cargo:rerun-if-changed=../{}/Cargo.toml", member_rel);
    }
    println!("cargo:rerun-if-changed=build.rs");
}

/// Parse the `members = [...]` array from a workspace `Cargo.toml`.
///
/// Handles the common multi-line form:
///
/// ```toml
/// [workspace]
/// members = [
///     "crabport-core",
///     "crabport-ssh",
///     ...
/// ]
/// ```
///
/// Returns the list of member path strings. Unknown / missing array → empty.
fn parse_workspace_members(toml: &str) -> Vec<String> {
    let mut members = Vec::new();
    let mut in_workspace = false;
    let mut in_members_array = false;

    for line in toml.lines() {
        let trimmed = line.trim();

        if trimmed.starts_with('[') {
            in_workspace = trimmed == "[workspace]";
            in_members_array = false;
            continue;
        }

        if !in_workspace {
            continue;
        }

        if !in_members_array {
            // Look for `members = [`
            if let Some(rest) = trimmed.strip_prefix("members") {
                let rest = rest.trim_start();
                if let Some(rest) = rest.strip_prefix('=') {
                    let rest = rest.trim_start();
                    if rest.starts_with('[') {
                        in_members_array = true;
                        // The array may close on the same line.
                        if let Some(inner) = rest.strip_prefix('[') {
                            if let Some(inner) = inner.strip_suffix(']') {
                                // Single-line array.
                                if let Some(name) = parse_toml_string(inner.trim()) {
                                    members.push(name);
                                }
                                in_members_array = false;
                            } else {
                                // Multi-line: parse any string on this line.
                                if let Some(name) = parse_toml_string(inner.trim()) {
                                    members.push(name);
                                }
                            }
                        }
                    }
                }
            }
        } else {
            // Already inside the members array.
            if let Some(idx) = trimmed.find(']') {
                let before = &trimmed[..idx];
                if let Some(name) = parse_toml_string(before.trim()) {
                    members.push(name);
                }
                in_members_array = false;
            } else if let Some(name) = parse_toml_string(trimmed) {
                members.push(name);
            }
        }
    }

    members
}

/// Parse the keys of every `[dependencies]` table in a `Cargo.toml`.
///
/// Handles both inline-table and table forms:
///
/// ```toml
/// [dependencies]
/// foo = "1.0"
/// bar = { version = "2", features = ["x"] }
///
/// [dependencies.baz]
/// version = "3"
/// ```
///
/// `[dev-dependencies]`, `[build-dependencies]`, and target-specific deps
/// are intentionally NOT collected — the About list reflects runtime deps.
fn parse_dependencies_keys(toml: &str) -> Vec<String> {
    let mut keys = Vec::new();
    let mut current_section: Option<String> = None;
    // Track whether we're directly inside `[dependencies]` (not a sub-table
    // like `[dependencies.foo]`, which is handled separately below).
    let mut in_deps_table = false;

    for line in toml.lines() {
        let trimmed = line.trim();
        if trimmed.is_empty() || trimmed.starts_with('#') {
            continue;
        }

        if trimmed.starts_with('[') {
            // Section header. Strip brackets.
            let header = trimmed.trim_start_matches('[').trim_end_matches(']').trim();
            current_section = Some(header.to_string());
            // `[dependencies]` exactly → keys follow. `[dependencies.foo]`
            // is a sub-table whose key (`foo`) we capture below, but it has
            // no direct `key = value` dep lines of its own to collect.
            in_deps_table = header == "dependencies";
            // Sub-table form: `[dependencies.foo]` → register `foo`.
            if let Some(rest) = header.strip_prefix("dependencies.") {
                keys.push(rest.to_string());
            }
            continue;
        }

        if !in_deps_table {
            continue;
        }

        // Inside `[dependencies]`: the first `key = ...` token is the dep name.
        if let Some(eq_idx) = trimmed.find('=') {
            let key = trimmed[..eq_idx].trim();
            if !key.is_empty() && is_valid_dep_key(key) {
                keys.push(key.to_string());
            }
        }

        let _ = &current_section;
    }

    keys
}

/// A dependency key is a bare identifier (letters, digits, `-`, `_`).
/// Anything quoted or containing `.` is not a dep key.
fn is_valid_dep_key(s: &str) -> bool {
    !s.is_empty()
        && !s.starts_with('"')
        && s.chars()
            .all(|c| c.is_alphanumeric() || c == '-' || c == '_')
}

/// Parse a double-quoted TOML string out of `s`, returning the inner value.
/// Returns `None` if `s` doesn't contain a `"..."` segment.
fn parse_toml_string(s: &str) -> Option<String> {
    let s = s.trim();
    let start = s.find('"')?;
    let rest = &s[start + 1..];
    let end = rest.find('"')?;
    Some(rest[..end].to_string())
}

/// Parse `Cargo.lock` into a `name -> version` map.
///
/// Only the first occurrence of each name is kept (Cargo.lock shouldn't have
/// duplicates, but if a name appears under multiple sources we just take the
/// first).
fn parse_lock_packages(lock: &str) -> BTreeMap<String, String> {
    let mut map = BTreeMap::new();
    let mut in_package = false;
    let mut name = String::new();
    let mut version = String::new();

    for line in lock.lines() {
        let trimmed = line.trim();

        if trimmed.starts_with('[') {
            if in_package && !name.is_empty() {
                map.entry(name.clone()).or_insert_with(|| version.clone());
            }
            name.clear();
            version.clear();
            in_package = trimmed == "[[package]]";
            continue;
        }

        if !in_package {
            continue;
        }

        if let Some(rest) = trimmed.strip_prefix("name =") {
            name = strip_quotes(rest);
        } else if let Some(rest) = trimmed.strip_prefix("version =") {
            version = strip_quotes(rest);
        }
    }

    if in_package && !name.is_empty() {
        map.entry(name).or_insert(version);
    }

    map
}

fn strip_quotes(s: &str) -> String {
    let s = s.trim().trim_end_matches(',').trim();
    if s.len() >= 2 && s.starts_with('"') && s.ends_with('"') {
        s[1..s.len() - 1].to_string()
    } else {
        s.to_string()
    }
}
