use std::borrow::Cow;

use gpui::AssetSource;

// Generated by `build.rs` from every file under `crabport-ui/assets/`.
// Keys are forward-slash paths relative to `assets/` (e.g. "icons/foo.svg"),
// values are the file bytes embedded via `include_bytes!`.
//
// Embedding assets into the binary makes the app self-contained: packaged
// distributions (.app / raw .exe / raw Linux binary) don't need the original
// source tree's `assets/` directory to be present at runtime.
include!(concat!(env!("OUT_DIR"), "/embedded_assets.rs"));

pub struct CrabportAssets;

impl CrabportAssets {
    pub fn new() -> Self {
        Self
    }
}

impl AssetSource for CrabportAssets {
    fn load(&self, path: &str) -> gpui::Result<Option<Cow<'static, [u8]>>> {
        // `path` may arrive with a leading slash (e.g. "/icons/foo.svg")
        // depending on the caller; normalise by trimming leading slashes.
        let key = path.trim_start_matches('/');
        Ok(EMBEDDED_ASSETS
            .iter()
            .find(|(k, _)| *k == key)
            .map(|(_, data)| Cow::Borrowed(*data)))
    }

    fn list(&self, path: &str) -> gpui::Result<Vec<gpui::SharedString>> {
        // `path` is a directory prefix relative to `assets/` (e.g. "icons").
        // List immediate children (files and subdirs) under that prefix.
        let prefix = path.trim_start_matches('/');
        let prefix = if prefix.is_empty() {
            String::new()
        } else if prefix.ends_with('/') {
            prefix.to_string()
        } else {
            format!("{prefix}/")
        };

        let mut seen = std::collections::BTreeSet::new();
        for (k, _) in EMBEDDED_ASSETS {
            if let Some(rest) = k.strip_prefix(&prefix) {
                // Immediate child = first path segment of `rest`.
                if let Some(segment) = rest.split('/').next() {
                    if !segment.is_empty() {
                        seen.insert(segment.to_string());
                    }
                }
            }
        }

        Ok(seen.into_iter().map(gpui::SharedString::from).collect())
    }
}
